# action.yml
name: 'Heroku Jar Deploy'
description: ''
inputs:
  heroku-api-key:
    description: ''
    required: true
  jdk:
    description: ''
    required: true
  jar-path:
    description: ''
    required: true
  app-name:
    description: ''
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    HEROKU_API_KEY: ${{ inputs.heroku-api-key }}
  args:
    # ie. heroku jar:deploy --jdk 11 --jar build/libs/demo-0.0.1-SNAPSHOT.jar --app infinite-caverns-43687
    - jar:deploy
    - --jdk
    - ${{ inputs.jdk }}
    - --jar
    - ${{ inputs.jar-path }}
    - --app
    - ${{ inputs.app-name }}