# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with custom docker action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Deploy to staging
        uses: ./ # Uses an action in the root directory
        id: heroku-jar-deploy
        with:
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}
          jdk: 11
          jar-path: build/libs/demo-0.0.1-SNAPSHOT.jar
          app-name: infinite-caverns-43687
      - name: Component Tests
        run: 'echo -n "Main page..."; test "$(curl --fail --silent https://infinite-caverns-43687.herokuapp.com/ | jq -r ''.tip'')" == "Do It Yourself!" && echo "passed." || echo "failed. Bad main page"'
      - name: Deploy to production
        uses: ./ # Uses an action in the root directory
        id: heroku-jar-deploy
        with:
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}
          jdk: 11
          jar-path: build/libs/demo-0.0.1-SNAPSHOT.jar
          app-name: quiet-shelf-20036
