# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle, Bash and Heroku

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Install heroku jar plugin
        run: heroku plugins:install java
      - name: Deploy to staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        # heroku cli is installed
        run: heroku jar:deploy --jdk 11 --jar build/libs/github-demo-0.0.1-SNAPSHOT.jar --app infinite-caverns-43687
      - name: Component Tests
        run: 'echo -n "Main page..."; test "$(curl --fail --silent https://infinite-caverns-43687.herokuapp.com/ | jq -r ''.tip'')" == "Do It Yourself!" && echo "passed." || echo "failed. Bad main page"'
      - name: Deploy to production
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku jar:deploy --jdk 11 --jar build/libs/github-demo-0.0.1-SNAPSHOT.jar --app quiet-shelf-20036
